### ISSUE TITLE
Database link not working

### ISSUE THREAD

**Issue by Andrewab9** [nekokoe/Plasmer#6]
Hello, i was interested into Plasmer but i can't download the pre-built database. Is there any other way to download it?

**Comment by iskoldt-X** [comment]
Hi Andrewab9, thank you for your interest in Plasmer. Our article is currently under review and has not yet been published. As a result, the database resource remains unpublished as well. Would it be possible for you to wait a little longer? I will notify you as soon as everything is ready. Thank you for your patience and understanding.

**Comment by iskoldt-X** [comment]
Hi Andrewab9, we have published the database today. You can try it at https://doi.org/10.5281/zenodo.7030674 
or https://drive.google.com/drive/folders/1C1XLqTuPVfwyB7N3b5QAU09Rn-Qq7RdD?usp=sharing 
Please notice that the program and database had been updated, you may need to install the latest version 😁
